FROM node:lts-alpine
WORKDIR /app
COPY ./dist/apps/study-data-pod .
COPY ./project.json yarn.lock ./
ENV PORT=3334
EXPOSE ${PORT}
RUN npm install --production
# dependencies that express needs
RUN npm install reflect-metadata tslib rxjs express
CMD node ./main.js
